# -*- coding: utf-8 -*-
{
    'name': 'Trevi Style Theme',
    'description': 'E-commerce fashion website theme inspired by Haravan Trevi Style',
    'category': 'Theme',
    'sequence': 1000,
    'version': '3.0',
    'depends': ['website', 'website_sale', 'website_blog'],
    'data': [
        'data/theme_data.xml',
        'data/demo_data.xml',
        'views/website_templates.xml',
        'views/snippet_templates.xml',
        'views/snippets.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            # SCSS - Core
            'theme_evo_fashion/static/src/scss/_main.scss',
            'theme_evo_fashion/static/src/scss/_topbar.scss',
            'theme_evo_fashion/static/src/scss/_announcement_bar.scss',
            # SCSS - Components
            'theme_evo_fashion/static/src/scss/_hero_slider.scss',
            'theme_evo_fashion/static/src/scss/_banner_grid.scss',
            'theme_evo_fashion/static/src/scss/_category_carousel.scss',
            'theme_evo_fashion/static/src/scss/_flash_sale.scss',
            'theme_evo_fashion/static/src/scss/_coupon.scss',
            'theme_evo_fashion/static/src/scss/_product_card.scss',
            'theme_evo_fashion/static/src/scss/_product_tabs.scss',
            'theme_evo_fashion/static/src/scss/_collection.scss',
            'theme_evo_fashion/static/src/scss/_bottom_banner.scss',
            'theme_evo_fashion/static/src/scss/_handmade.scss',
            'theme_evo_fashion/static/src/scss/_service_features.scss',
            'theme_evo_fashion/static/src/scss/_blog.scss',
            'theme_evo_fashion/static/src/scss/_instagram.scss',
            'theme_evo_fashion/static/src/scss/_feedback.scss',
            'theme_evo_fashion/static/src/scss/_intro.scss',
            'theme_evo_fashion/static/src/scss/_policy.scss',
            'theme_evo_fashion/static/src/scss/_footer.scss',
            'theme_evo_fashion/static/src/scss/_modal.scss',
            'theme_evo_fashion/static/src/scss/_homepage.scss',
            # JS - OWL 2 Components
            'theme_evo_fashion/static/src/js/announcement_bar.js',
            'theme_evo_fashion/static/src/js/hero_slider.js',
            'theme_evo_fashion/static/src/js/banner_grid.js',
            'theme_evo_fashion/static/src/js/category_carousel.js',
            'theme_evo_fashion/static/src/js/flash_sale.js',
            'theme_evo_fashion/static/src/js/product_card.js',
            'theme_evo_fashion/static/src/js/product_tabs.js',
            'theme_evo_fashion/static/src/js/service_features.js',
            'theme_evo_fashion/static/src/js/footer.js',
            'theme_evo_fashion/static/src/js/homepage.js',
        ],
    },
    'images': [
        'static/description/icon.png',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
}
